# Generated by Django 3.2.1 on 2023-05-08 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_alter_question_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={},
        ),
    ]
